export let lightThemeArray = [
    // Material Design配色
    {'bodyBackgroundColor': '#FFEBEE', 'frostedGlassBackgroundColor': '#F44336'},
    {'bodyBackgroundColor': '#F44336', 'frostedGlassBackgroundColor': '#FFEBEE'},
    {'bodyBackgroundColor': '#FCE4EC', 'frostedGlassBackgroundColor': '#E91E63'},
    {'bodyBackgroundColor': '#E91E63', 'frostedGlassBackgroundColor': '#FCE4EC'},
    {'bodyBackgroundColor': '#F3E5F5', 'frostedGlassBackgroundColor': '#9C27B0'},
    {'bodyBackgroundColor': '#9C27B0', 'frostedGlassBackgroundColor': '#F3E5F5'},
    {'bodyBackgroundColor': '#EDE7F6', 'frostedGlassBackgroundColor': '#673AB7'},
    {'bodyBackgroundColor': '#673AB7', 'frostedGlassBackgroundColor': '#EDE7F6'},
    {'bodyBackgroundColor': '#E8EAF6', 'frostedGlassBackgroundColor': '#3F51B5'},
    {'bodyBackgroundColor': '#3F51B5', 'frostedGlassBackgroundColor': '#E8EAF6'},
    {'bodyBackgroundColor': '#E3F2FD', 'frostedGlassBackgroundColor': '#2196F3'},
    {'bodyBackgroundColor': '#2196F3', 'frostedGlassBackgroundColor': '#E3F2FD'},
    {'bodyBackgroundColor': '#E1F5FE', 'frostedGlassBackgroundColor': '#03A9F4'},
    {'bodyBackgroundColor': '#03A9F4', 'frostedGlassBackgroundColor': '#E1F5FE'},
    {'bodyBackgroundColor': '#E0F7FA', 'frostedGlassBackgroundColor': '#00BCD4'},
    {'bodyBackgroundColor': '#00BCD4', 'frostedGlassBackgroundColor': '#E0F7FA'},
    {'bodyBackgroundColor': '#E0F2F1', 'frostedGlassBackgroundColor': '#009688'},
    {'bodyBackgroundColor': '#009688', 'frostedGlassBackgroundColor': '#E0F2F1'},
    {'bodyBackgroundColor': '#E8F5E9', 'frostedGlassBackgroundColor': '#4CAF50'},
    {'bodyBackgroundColor': '#4CAF50', 'frostedGlassBackgroundColor': '#E8F5E9'},
    {'bodyBackgroundColor': '#F1F8E9', 'frostedGlassBackgroundColor': '#8BC34A'},
    {'bodyBackgroundColor': '#8BC34A', 'frostedGlassBackgroundColor': '#F1F8E9'},
    {'bodyBackgroundColor': '#F9FBE7', 'frostedGlassBackgroundColor': '#CDDC39'},
    {'bodyBackgroundColor': '#CDDC39', 'frostedGlassBackgroundColor': '#F9FBE7'},
    {'bodyBackgroundColor': '#FFFDE7', 'frostedGlassBackgroundColor': '#FFEB3B'},
    {'bodyBackgroundColor': '#FFEB3B', 'frostedGlassBackgroundColor': '#FFFDE7'},
    {'bodyBackgroundColor': '#FFF8E1', 'frostedGlassBackgroundColor': '#FFC107'},
    {'bodyBackgroundColor': '#FFC107', 'frostedGlassBackgroundColor': '#FFF8E1'},
    {'bodyBackgroundColor': '#FFF3E0', 'frostedGlassBackgroundColor': '#FF9800'},
    {'bodyBackgroundColor': '#FF9800', 'frostedGlassBackgroundColor': '#FFF3E0'},
    {'bodyBackgroundColor': '#FBE9E7', 'frostedGlassBackgroundColor': '#FF5722'},
    {'bodyBackgroundColor': '#FF5722', 'frostedGlassBackgroundColor': '#FBE9E7'},
    {'bodyBackgroundColor': '#EFEBE9', 'frostedGlassBackgroundColor': '#795548'},
    {'bodyBackgroundColor': '#795548', 'frostedGlassBackgroundColor': '#EFEBE9'},
    {'bodyBackgroundColor': '#ECEFF1', 'frostedGlassBackgroundColor': '#607D8B'},
    {'bodyBackgroundColor': '#607D8B', 'frostedGlassBackgroundColor': '#ECEFF1'},
    {'bodyBackgroundColor': '#FAFAFA', 'frostedGlassBackgroundColor': '#9E9E9E'},
    {'bodyBackgroundColor': '#9E9E9E', 'frostedGlassBackgroundColor': '#FAFAFA'},

    // 高级配色
    {'bodyBackgroundColor': '#FAEFDE', 'frostedGlassBackgroundColor': '#E42D44'},
    {'bodyBackgroundColor': '#E42D44', 'frostedGlassBackgroundColor': '#FAEFDE'},
    {'bodyBackgroundColor': '#F2EAE0', 'frostedGlassBackgroundColor': '#7BAD5F'},
    {'bodyBackgroundColor': '#7BAD5F', 'frostedGlassBackgroundColor': '#F2EAE0'},
    {'bodyBackgroundColor': '#E5D7AD', 'frostedGlassBackgroundColor': '#614F4D'},
    {'bodyBackgroundColor': '#614F4D', 'frostedGlassBackgroundColor': '#E5D7AD'},
    {'bodyBackgroundColor': '#5B3663', 'frostedGlassBackgroundColor': '#FFD800'},
    // {'bodyBackgroundColor': '#FFD800', 'frostedGlassBackgroundColor': '#5B3663'},
    {'bodyBackgroundColor': '#BCCF90', 'frostedGlassBackgroundColor': '#F6A09A'},
    {'bodyBackgroundColor': '#F6A09A', 'frostedGlassBackgroundColor': '#BCCF90'},
    {'bodyBackgroundColor': '#343130', 'frostedGlassBackgroundColor': '#FF7900'},
    //{'bodyBackgroundColor': '#FF7900', 'frostedGlassBackgroundColor': '#343130'},
    {'bodyBackgroundColor': '#EDB04C', 'frostedGlassBackgroundColor': '#8A3C48'},
    {'bodyBackgroundColor': '#8A3C48', 'frostedGlassBackgroundColor': '#EDB04C'},
    {'bodyBackgroundColor': '#A0C198', 'frostedGlassBackgroundColor': '#535E4B'},
    {'bodyBackgroundColor': '#535E4B', 'frostedGlassBackgroundColor': '#A0C198'},
    {'bodyBackgroundColor': '#CFA33E', 'frostedGlassBackgroundColor': '#262424'},
    {'bodyBackgroundColor': '#262424', 'frostedGlassBackgroundColor': '#CFA33E'},
    {'bodyBackgroundColor': '#D23538', 'frostedGlassBackgroundColor': '#36527D'},
    {'bodyBackgroundColor': '#36527D', 'frostedGlassBackgroundColor': '#D23538'},
    {'bodyBackgroundColor': '#F7F2ED', 'frostedGlassBackgroundColor': '#8D587E'},
    {'bodyBackgroundColor': '#8D587E', 'frostedGlassBackgroundColor': '#F7F2ED'},

    {'bodyBackgroundColor': '#FD454A', 'frostedGlassBackgroundColor': '#FCBE23'},
    // {'bodyBackgroundColor': '#FCBE23', 'frostedGlassBackgroundColor': '#FD454A'},
    {'bodyBackgroundColor': '#4C3C36', 'frostedGlassBackgroundColor': '#7CAC67'},
    {'bodyBackgroundColor': '#7CAC67', 'frostedGlassBackgroundColor': '#4C3C36'},
    {'bodyBackgroundColor': '#013372', 'frostedGlassBackgroundColor': '#C9AB70'},
    {'bodyBackgroundColor': '#C9AB70', 'frostedGlassBackgroundColor': '#013372'},
    {'bodyBackgroundColor': '#F4EEE6', 'frostedGlassBackgroundColor': '#362228'},
    {'bodyBackgroundColor': '#362228', 'frostedGlassBackgroundColor': '#F4EEE6'},
    {'bodyBackgroundColor': '#C92C35', 'frostedGlassBackgroundColor': '#044091'},
    {'bodyBackgroundColor': '#044091', 'frostedGlassBackgroundColor': '#C92C35'},
    {'bodyBackgroundColor': '#A2DDB8', 'frostedGlassBackgroundColor': '#F6F2EB'},
    {'bodyBackgroundColor': '#F6F2EB', 'frostedGlassBackgroundColor': '#A2DDB8'},
    {'bodyBackgroundColor': '#FFCE56', 'frostedGlassBackgroundColor': '#7F8284'},
    {'bodyBackgroundColor': '#7F8284', 'frostedGlassBackgroundColor': '#FFCE56'},
    {'bodyBackgroundColor': '#6D8158', 'frostedGlassBackgroundColor': '#245776'},
    {'bodyBackgroundColor': '#245776', 'frostedGlassBackgroundColor': '#6D8158'},
    {'bodyBackgroundColor': '#CEBECE', 'frostedGlassBackgroundColor': '#EFF2FA'},
    {'bodyBackgroundColor': '#EFF2FA', 'frostedGlassBackgroundColor': '#CEBECE'},
    {'bodyBackgroundColor': '#DCB28C', 'frostedGlassBackgroundColor': '#474361'},
    {'bodyBackgroundColor': '#474361', 'frostedGlassBackgroundColor': '#DCB28C'},
    {'bodyBackgroundColor': '#50543B', 'frostedGlassBackgroundColor': '#FFE7B6'},
    {'bodyBackgroundColor': '#FFE7B6', 'frostedGlassBackgroundColor': '#50543B'},
];

export let darkThemeArray = [
    // Material Design配色
    {'bodyBackgroundColor': '#9C27B0', 'frostedGlassBackgroundColor': '#F3E5F5'},
    {'bodyBackgroundColor': '#673AB7', 'frostedGlassBackgroundColor': '#EDE7F6'},
    {'bodyBackgroundColor': '#3F51B5', 'frostedGlassBackgroundColor': '#E8EAF6'},
    {'bodyBackgroundColor': '#2196F3', 'frostedGlassBackgroundColor': '#E3F2FD'},
    {'bodyBackgroundColor': '#03A9F4', 'frostedGlassBackgroundColor': '#E1F5FE'},
    {'bodyBackgroundColor': '#00BCD4', 'frostedGlassBackgroundColor': '#E0F7FA'},
    {'bodyBackgroundColor': '#009688', 'frostedGlassBackgroundColor': '#E0F2F1'},
    {'bodyBackgroundColor': '#4CAF50', 'frostedGlassBackgroundColor': '#E8F5E9'},
    {'bodyBackgroundColor': '#8BC34A', 'frostedGlassBackgroundColor': '#F1F8E9'},
    {'bodyBackgroundColor': '#795548', 'frostedGlassBackgroundColor': '#EFEBE9'},
    {'bodyBackgroundColor': '#607D8B', 'frostedGlassBackgroundColor': '#ECEFF1'},
    {'bodyBackgroundColor': '#9E9E9E', 'frostedGlassBackgroundColor': '#FAFAFA'},

    // 高级配色
    {'bodyBackgroundColor': '#7BAD5F', 'frostedGlassBackgroundColor': '#F2EAE0'},
    {'bodyBackgroundColor': '#614F4D', 'frostedGlassBackgroundColor': '#E5D7AD'},
    {'bodyBackgroundColor': '#5B3663', 'frostedGlassBackgroundColor': '#FFD800'},
    {'bodyBackgroundColor': '#BCCF90', 'frostedGlassBackgroundColor': '#F6A09A'},
    {'bodyBackgroundColor': '#F6A09A', 'frostedGlassBackgroundColor': '#BCCF90'},
    {'bodyBackgroundColor': '#343130', 'frostedGlassBackgroundColor': '#FF7900'},
    {'bodyBackgroundColor': '#EDB04C', 'frostedGlassBackgroundColor': '#8A3C48'},
    {'bodyBackgroundColor': '#8A3C48', 'frostedGlassBackgroundColor': '#EDB04C'},
    {'bodyBackgroundColor': '#A0C198', 'frostedGlassBackgroundColor': '#535E4B'},
    {'bodyBackgroundColor': '#535E4B', 'frostedGlassBackgroundColor': '#A0C198'},
    {'bodyBackgroundColor': '#CFA33E', 'frostedGlassBackgroundColor': '#262424'},
    {'bodyBackgroundColor': '#262424', 'frostedGlassBackgroundColor': '#CFA33E'},
    {'bodyBackgroundColor': '#36527D', 'frostedGlassBackgroundColor': '#D23538'},
    {'bodyBackgroundColor': '#8D587E', 'frostedGlassBackgroundColor': '#F7F2ED'},

    {'bodyBackgroundColor': '#4C3C36', 'frostedGlassBackgroundColor': '#7CAC67'},
    {'bodyBackgroundColor': '#7CAC67', 'frostedGlassBackgroundColor': '#4C3C36'},
    {'bodyBackgroundColor': '#013372', 'frostedGlassBackgroundColor': '#C9AB70'},
    {'bodyBackgroundColor': '#C9AB70', 'frostedGlassBackgroundColor': '#013372'},
    {'bodyBackgroundColor': '#362228', 'frostedGlassBackgroundColor': '#F4EEE6'},
    {'bodyBackgroundColor': '#C92C35', 'frostedGlassBackgroundColor': '#044091'},
    {'bodyBackgroundColor': '#044091', 'frostedGlassBackgroundColor': '#C92C35'},
    {'bodyBackgroundColor': '#A2DDB8', 'frostedGlassBackgroundColor': '#F6F2EB'},
    {'bodyBackgroundColor': '#7F8284', 'frostedGlassBackgroundColor': '#FFCE56'},
    {'bodyBackgroundColor': '#6D8158', 'frostedGlassBackgroundColor': '#245776'},
    {'bodyBackgroundColor': '#245776', 'frostedGlassBackgroundColor': '#6D8158'},
    {'bodyBackgroundColor': '#CEBECE', 'frostedGlassBackgroundColor': '#EFF2FA'},
    {'bodyBackgroundColor': '#DCB28C', 'frostedGlassBackgroundColor': '#474361'},
    {'bodyBackgroundColor': '#474361', 'frostedGlassBackgroundColor': '#DCB28C'},
    {'bodyBackgroundColor': '#50543B', 'frostedGlassBackgroundColor': '#FFE7B6'},
];