export let themes = [
    {'bodyBackgroundColor': '#FFEBEE', 'frostedGlassBackgroundColor': '#F44336'},
    {'bodyBackgroundColor': '#FCE4EC', 'frostedGlassBackgroundColor': '#E91E63'},
    {'bodyBackgroundColor': '#F3E5F5', 'frostedGlassBackgroundColor': '#9C27B0'},
    {'bodyBackgroundColor': '#EDE7F6', 'frostedGlassBackgroundColor': '#673AB7'},
    {'bodyBackgroundColor': '#E8EAF6', 'frostedGlassBackgroundColor': '#3F51B5'},
    {'bodyBackgroundColor': '#E3F2FD', 'frostedGlassBackgroundColor': '#2196F3'},
    {'bodyBackgroundColor': '#E1F5FE', 'frostedGlassBackgroundColor': '#03A9F4'},
    {'bodyBackgroundColor': '#E0F7FA', 'frostedGlassBackgroundColor': '#00BCD4'},
    {'bodyBackgroundColor': '#E0F2F1', 'frostedGlassBackgroundColor': '#009688'},
    {'bodyBackgroundColor': '#E8F5E9', 'frostedGlassBackgroundColor': '#4CAF50'},
    {'bodyBackgroundColor': '#F1F8E9', 'frostedGlassBackgroundColor': '#8BC34A'},
    {'bodyBackgroundColor': '#F9FBE7', 'frostedGlassBackgroundColor': '#CDDC39'},
    {'bodyBackgroundColor': '#FFFDE7', 'frostedGlassBackgroundColor': '#FFEB3B'},
    {'bodyBackgroundColor': '#FFF8E1', 'frostedGlassBackgroundColor': '#FFC107'},
    {'bodyBackgroundColor': '#FFF3E0', 'frostedGlassBackgroundColor': '#FF9800'},
    {'bodyBackgroundColor': '#FBE9E7', 'frostedGlassBackgroundColor': '#FF5722'},
    {'bodyBackgroundColor': '#EFEBE9', 'frostedGlassBackgroundColor': '#795548'},
    {'bodyBackgroundColor': '#ECEFF1', 'frostedGlassBackgroundColor': '#607D8B'},
    {'bodyBackgroundColor': '#FAFAFA', 'frostedGlassBackgroundColor': '#9E9E9E'},

    {'bodyBackgroundColor': '#FAEFDE', 'frostedGlassBackgroundColor': '#E42D44'},
    {'bodyBackgroundColor': '#F2EAE0', 'frostedGlassBackgroundColor': '#7BAD5F'},
    {'bodyBackgroundColor': '#E5D7AD', 'frostedGlassBackgroundColor': '#614F4D'},
    {'bodyBackgroundColor': '#5B3663', 'frostedGlassBackgroundColor': '#FFD800'},
    {'bodyBackgroundColor': '#BCCF90', 'frostedGlassBackgroundColor': '#F6A09A'},
    {'bodyBackgroundColor': '#343130', 'frostedGlassBackgroundColor': '#FF7900'},
    {'bodyBackgroundColor': '#EDB04C', 'frostedGlassBackgroundColor': '#8A3C48'},
    {'bodyBackgroundColor': '#A0C198', 'frostedGlassBackgroundColor': '#535E4B'},
    {'bodyBackgroundColor': '#CFA33E', 'frostedGlassBackgroundColor': '#262424'},
    {'bodyBackgroundColor': '#D23538', 'frostedGlassBackgroundColor': '#36527D'},
    {'bodyBackgroundColor': '#F7F2ED', 'frostedGlassBackgroundColor': '#8D587E'},
]